In [43]:
import numpy as np
import matplotlib.pyplot as plt
import h5py
import scipy
from PIL import Image
from scipy import ndimage
# from lr_utils import load_dataset
import pandas as pd
import tensorflow as tf

In [44]:
url="https://raw.githubusercontent.com/gautam0831/CS230_Project/main/crunchbase-oct-2013/crunchbase-companies.csv"
path="https://raw.githubusercontent.com/gautam0831/CS230_Project/main/crunchbase-oct-2013/"
files_in_path=["crunchbase-acquisitions.csv","crunchbase-companies.csv","crunchbase-investments.csv", "crunchbase-rounds.csv"]
dicts = {}
for i in range(len(files_in_path)):
  fname = pd.read_csv(path+files_in_path[i], error_bad_lines=False, encoding='latin-1')
  dicts[files_in_path[i]] = fname
  #print(dicts[files_in_path[i]])
#c=pd.read_csv(url, error_bad_lines=False, encoding='latin-1')
#print(c)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [45]:
file1 = pd.read_csv(path+files_in_path[0], error_bad_lines=False, encoding='latin-1')
print(file1.columns)

Index(['company_permalink', 'company_name', 'company_category_code',
       'company_country_code', 'company_state_code', 'company_region',
       'company_city', 'acquirer_permalink', 'acquirer_name',
       'acquirer_category_code', 'acquirer_country_code',
       'acquirer_state_code', 'acquirer_region', 'acquirer_city',
       'acquired_at', 'acquired_month', 'acquired_quarter', 'acquired_year',
       'price_amount', 'price_currency_code'],
      dtype='object')

In [46]:
file2 = pd.read_csv(path+files_in_path[1], error_bad_lines=False, encoding='latin-1')
file3 = pd.read_csv(path+files_in_path[2], error_bad_lines=False, encoding='latin-1')
file4 = pd.read_csv(path+files_in_path[3], error_bad_lines=False, encoding='latin-1')
print(file4.columns)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Index(['company_permalink', 'company_name', 'company_category_code',
       'company_country_code', 'company_state_code', 'company_region',
       'company_city', 'funding_round_type', 'funded_at', 'funded_month',
       'funded_quarter', 'funded_year', 'raised_amount_usd'],
      dtype='object')

In [47]:
combined = pd.merge(file1, file2, left_on = "company_permalink", right_on = "permalink", how = "inner")
#combined.head()
combined2 = pd.merge(combined, file3, on = "company_permalink", how = "inner")
combined2.head()

       company_permalink company_name_x  ... funded_year raised_amount_usd
0  /company/1000memories   1000memories  ...      2010.0           15000.0
1  /company/1000memories   1000memories  ...      2011.0         2520000.0
2  /company/1000memories   1000memories  ...      2011.0         2520000.0
3  /company/1000memories   1000memories  ...      2010.0           15000.0
4  /company/1000memories   1000memories  ...      2011.0         2520000.0

[5 rows x 56 columns]

In [48]:
#Filter for just US Companies
combined = combined[combined["company_country_code"] == "USA"]